# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-17 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_auto_20160817_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Pauta')),
            ],
            options={
                'verbose_name': 'Pauta',
                'verbose_name_plural': 'Pautas',
            },
        ),
        migrations.AlterModelOptions(
            name='politicalparty',
            options={'verbose_name': 'partido político', 'verbose_name_plural': 'partidos políticos'},
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='directory_city',
            field=models.TextField(verbose_name='diretório municipal'),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='directory_national',
            field=models.TextField(verbose_name='diretório nacional'),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='directory_state',
            field=models.TextField(verbose_name='diretório estadual'),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='initials',
            field=models.CharField(max_length=128, verbose_name='sigla'),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='name',
            field=models.CharField(max_length=128, verbose_name='nome'),
        ),
    ]
