# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-17 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_auto_20160817_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='agenda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='candidates.Agenda', verbose_name='Pauta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='projects',
            field=models.TextField(default=1, verbose_name='Projetos'),
            preserve_default=False,
        ),
    ]
