# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-20 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_candidate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], default='F', max_length=1, verbose_name='sexo'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nome'),
        ),
    ]
