# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-20 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_auto_20160820_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='picture',
            field=models.CharField(default=1, max_length=256, verbose_name='Foto'),
            preserve_default=False,
        ),
    ]
