# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-20 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_politicalparty_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Pauta',
                'verbose_name_plural': 'Pautas',
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='candidates.JobRole', verbose_name='Cargo'),
            preserve_default=False,
        ),
    ]
