# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-21 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_auto_20160820_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobrole',
            options={'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
    ]
