# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-21 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_candidate_name_ballot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalparty',
            name='directory_city',
            field=models.TextField(blank=True, verbose_name='diretório municipal'),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='directory_national',
            field=models.TextField(blank=True, verbose_name='diretório nacional'),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='directory_state',
            field=models.TextField(blank=True, verbose_name='diretório estadual'),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='obs',
            field=models.TextField(blank=True),
        ),
    ]
