# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-21 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0013_auto_20160821_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='agenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.Agenda', verbose_name='Pauta'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='picture_url',
            field=models.CharField(max_length=256, null=True, verbose_name='URL da foto'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='projects',
            field=models.TextField(blank=True, verbose_name='Projetos'),
        ),
    ]
