# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-21 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_auto_20160821_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='picture_url',
            field=models.CharField(default=1, max_length=256, verbose_name='URL da foto'),
            preserve_default=False,
        ),
    ]
