# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0015_auto_20160821_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='birth_date',
            field=models.DateField(default='2016-01-01', verbose_name='Data de nascimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='budget_1t',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19, verbose_name='Orçamento 1.o turno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='budget_2t',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19, verbose_name='Orçamento 2.o turno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='coalition',
            field=models.CharField(default=1, max_length=128, verbose_name='Coligação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='education',
            field=models.CharField(default=1, max_length=128, verbose_name='Nível escolaridade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='elected',
            field=models.BooleanField(default=1, verbose_name='Eleita antes de 2012?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='facebook',
            field=models.URLField(null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='id_tse',
            field=models.IntegerField(default=1, verbose_name='ID do TSE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='instagram',
            field=models.URLField(null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.CharField(default=1, max_length=128, verbose_name='Ocupação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='marital_status',
            field=models.CharField(default=1, max_length=128, verbose_name='Estado civil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='property_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Total de bens'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='reelection',
            field=models.BooleanField(default=1, verbose_name='Re-eleição?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('D', 'Negado')], default='P', max_length=1, verbose_name='Aprovação candidatura Mulheres do Brasil'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='twitter',
            field=models.URLField(null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], default='F', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='number',
            field=models.IntegerField(verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='picture_url',
            field=models.URLField(verbose_name='URL da foto'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='political_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.PoliticalParty', verbose_name='Partido'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='projects',
            field=models.TextField(null=True, verbose_name='Projetos'),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='directory_city',
            field=models.TextField(null=True, verbose_name='diretório municipal'),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='directory_national',
            field=models.TextField(null=True, verbose_name='diretório nacional'),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='directory_state',
            field=models.TextField(null=True, verbose_name='diretório estadual'),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='obs',
            field=models.TextField(null=True),
        ),
    ]
