# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0017_auto_20160822_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='birth_date',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
    ]
