# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0019_auto_20160822_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_id', models.IntegerField(verbose_name='Facebook')),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
                ('comment', models.TextField(blank=True, verbose_name='Comentário')),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
            },
        ),
        migrations.AlterField(
            model_name='candidate',
            name='agenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.Agenda', verbose_name='Pauta'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='birth_date',
            field=models.DateField(blank=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='projects',
            field=models.TextField(blank=True, verbose_name='Projetos'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='comments',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate', verbose_name='Candidata'),
        ),
    ]
