# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0022_auto_20160830_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrole',
            name='code',
            field=models.CharField(max_length=128, null=True, verbose_name='C\xf3digo'),
        ),
        migrations.AddField(
            model_name='jobrole',
            name='counting',
            field=models.IntegerField(default=0, verbose_name='Contagem'),
        ),
        migrations.AddField(
            model_name='jobrole',
            name='initials',
            field=models.CharField(max_length=128, null=True, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='budget_1t',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name=b'Or\xc3\xa7amento 1.o turno'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='budget_2t',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name=b'Or\xc3\xa7amento 2.o turno'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='coalition',
            field=models.CharField(max_length=128, verbose_name=b'Coliga\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='education',
            field=models.CharField(max_length=128, verbose_name=b'N\xc3\xadvel escolaridade'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='job',
            field=models.CharField(max_length=128, verbose_name=b'Ocupa\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='reelection',
            field=models.BooleanField(default=False, verbose_name=b'Re-elei\xc3\xa7\xc3\xa3o?'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[(b'P', b'Pendente'), (b'A', b'Aprovado'), (b'D', b'Negado')], default=b'P', max_length=1, verbose_name=b'Aprova\xc3\xa7\xc3\xa3o candidatura Mulheres do Brasil'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, verbose_name=b'Coment\xc3\xa1rio'),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='directory_city',
            field=models.TextField(null=True, verbose_name=b'diret\xc3\xb3rio municipal'),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='directory_national',
            field=models.TextField(null=True, verbose_name=b'diret\xc3\xb3rio nacional'),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='directory_state',
            field=models.TextField(null=True, verbose_name=b'diret\xc3\xb3rio estadual'),
        ),
    ]
