# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-27 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0025_auto_20160902_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='budget_1t',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Limite de gasto 1.o turno'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='budget_2t',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Limite de gasto 2.o turno'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='id_tse',
            field=models.CharField(max_length=100, verbose_name='ID do TSE'),
        ),
    ]
