# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-04 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0027_auto_20180829_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=128, verbose_name='UF')),
                ('name', models.CharField(max_length=128, verbose_name='nome')),
            ],
        ),
        migrations.AddField(
            model_name='politicalparty',
            name='money_women_pct',
            field=models.FloatField(null=True, verbose_name='porcentagem de dinheiro destinado a mulheres'),
        ),
        migrations.AddField(
            model_name='politicalparty',
            name='ranking',
            field=models.IntegerField(null=True, verbose_name='ranking to partido'),
        ),
        migrations.AddField(
            model_name='politicalparty',
            name='size',
            field=models.IntegerField(null=True, verbose_name='tamanho do partido'),
        ),
        migrations.AddField(
            model_name='politicalparty',
            name='women_ptc',
            field=models.FloatField(null=True, verbose_name='porcentagem de mulheres'),
        ),
    ]
