# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-06 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0031_candidate_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyJobRoleStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(null=True, verbose_name='Número de candidatos nesse cargo por partido')),
                ('women_ptc', models.FloatField(null=True, verbose_name='porcentagem de mulheres')),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.JobRole', verbose_name='Cargo')),
                ('political_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.PoliticalParty', verbose_name='Partido')),
            ],
        ),
    ]
