# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-06 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0032_partyjobrolestats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrole',
            name='code',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Cargo'),
        ),
    ]
