# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-06 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0033_auto_20180906_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partyjobrolestats',
            old_name='women_ptc',
            new_name='women_pct',
        ),
    ]
