# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-06 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0034_auto_20180906_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='politicalparty',
            old_name='women_ptc',
            new_name='women_pct',
        ),
    ]
