# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-11 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0035_auto_20180906_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='budget_1t',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Limite de gasto 1.o turno'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='budget_2t',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Limite de gasto 2.o turno'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='picture_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL da foto'),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='initials',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Sigla'),
        ),
    ]
