# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-14 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0036_auto_20180911_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='icon',
            field=models.URLField(blank=True, max_length=255, verbose_name='ícone'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Pauta'),
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='agenda',
        ),
        migrations.AddField(
            model_name='candidate',
            name='agenda',
            field=models.ManyToManyField(null=True, to='candidates.Agenda', verbose_name='Pauta'),
        ),
    ]
