# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-14 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0037_auto_20180914_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='agenda',
            field=models.ManyToManyField(to='candidates.Agenda', verbose_name='Pauta'),
        ),
    ]
