# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-14 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0038_auto_20180914_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='icon',
            field=models.CharField(blank=True, max_length=255, verbose_name='ícone'),
        ),
    ]
